### ISSUE TITLE
Document how to use custom docker images

### ISSUE THREAD

**Issue by dlespiau** [dlespiau/footloose#26]
It's often useful to pre-seeed the machine image with packages we want installed. This can be easily done by deriving a footloose image and adding a few `RUN` steps. With then need to indicate the image we want to run in the config file.

We should document the above.

**Comment by rothgar** [comment]
Is there documentation on how to do this with a non footloose image? eg I would love to do with with [amazonlinux](https://hub.docker.com/_/amazonlinux) but am not sure what the images require to run in footloose.

**Comment by dlespiau** [comment]
Hi Justin,

There are two things:
- A base image with systemd, sshd and a few details needed to run systemd in a container (eg. `container` env variable, removing some unneeded unit files, ...). For that I created a new issue (#59). These base image could live in `quay.io/footloose/amazonlinux2`
- Once we have base image, you can create your own customisation of the base image, say by adding packages you need for what you're doing with the machine. It's just another docker image, deriving from one of the base images (`FROM quay.io/footloose/amazonlinux2`). That's what this issue is about.

I can look at providing a base image this week, maybe even today. Or you can try if you want to and have time :) (that's #59).

I'll put this issue in the 0.2.0 milestone, that's really an easy addition to the README in the example section, just need to think about a use case, say having docker pre-provisioned in the container machines.
